const dummyData = [
  {
    name: "Airbnb 1",
    bedrooms: 2,
    bathrooms: 1,
    price: { rate: 100 },
    previewAmenities: ["WiFi", "Pool"],
    images: ["https://dummyimage.com/300x225/000/fff"],
    deeplink: "https://www.example.com",
  },
  {
    name: "Airbnb 2",
    bedrooms: 3,
    bathrooms: 2,
    price: { rate: 200 },
    previewAmenities: ["WiFi", "Gym"],
    images: ["https://dummyimage.com/300x225/000/fff"],
    deeplink: "https://www.example.com",
  },
  {
    name: "Airbnb 3",
    bedrooms: 1,
    bathrooms: 1,
    price: { rate: 80 },
    previewAmenities: ["WiFi", "Kitchen"],
    images: ["https://dummyimage.com/300x225/000/fff"],
    deeplink: "https://www.example.com",
  },
  {
    name: "Airbnb 4",
    bedrooms: 4,
    bathrooms: 3,
    price: { rate: 350 },
    previewAmenities: ["WiFi", "Hot tub"],
    images: ["https://dummyimage.com/300x225/000/fff"],
    deeplink: "https://www.example.com",
  },
  {
    name: "Airbnb 5",
    bedrooms: 2,
    bathrooms: 2,
    price: { rate: 150 },
    previewAmenities: ["WiFi", "Parking"],
    images: ["https://dummyimage.com/300x225/000/fff"],
    deeplink: "https://www.example.com",
  },
  {
    name: "Airbnb 6",
    bedrooms: 1,
    bathrooms: 1,
    price: { rate: 60 },
    previewAmenities: ["WiFi", "Pet-friendly"],
    images: ["https://dummyimage.com/300x225/000/fff"],
    deeplink: "https://www.example.com",
  },
  {
    name: "Airbnb 7",
    bedrooms: 3,
    bathrooms: 2,
    price: { rate: 225 },
    previewAmenities: ["WiFi", "Balcony"],
    images: ["https://dummyimage.com/300x225/000/fff"],
    deeplink: "https://www.example.com",
  },
  {
    name: "Airbnb 8",
    bedrooms: 2,
    bathrooms: 1,
    price: { rate: 120 },
    previewAmenities: ["WiFi", "Fireplace"],
    images: ["https://dummyimage.com/300x225/000/fff"],
    deeplink: "https://www.example.com",
  },
  {
    name: "Airbnb 9",
    bedrooms: 1,
    bathrooms: 1,
    price: { rate: 70 },
    previewAmenities: ["WiFi", "Breakfast"],
    images: ["https://dummyimage.com/300x225/000/fff"],
    deeplink: "https://www.example.com",
  },
];

export default dummyData;
